Checking in the ability to run inferencing leveraging the bounding box data from Store API and added reference to env variables for Store APi and Footfall API
Azure/jumpstart-apps pull request #93
Opened 2024-10-28 22:43 UTC by nabeelmsft

Checking in the ability to run inferencing leveraging the bounding box data from Store API and added reference to env variables for Store APi and Footfall API.

2024-10-28 22:59 UTC, dkirby-ms requested changes

2024-10-28 22:59 UTC, dkirby-ms commented on agora/main_ui/src/.env
remove this dev file please

2024-10-29 00:05 UTC, nabeelmsft commented on agora/main_ui/src/.env
Done!

2024-10-29 00:49 UTC, dkirby-ms approved these changes

2024-10-29 00:49 UTC, merged